### ISSUE TITLE
Connect database

### ISSUE THREAD

**Issue by golu7679** [zigzap/zap#106]
I want to connect sql and no sql database, how can I do this in zap?

**Comment by renerocksai** [comment]
Zap is a microframework. Database connections are beyond its scope. You would connect to and use databases like in any other program. Meaning: If you can write a zig program that connects to a database, you can do the same in a zap app.

Google is your friend, there are zig packages for DBs like e.g. postgresql. Alternatively, use a C implementation.

Also look at the awesome [Jetzig Framework](https://www.jetzig.dev/) - I get the impression that it might be a better match for you.

**Comment by anthonycorletti** [comment]
@renerocksai stumbled onto this and was curious if working with a database would be as easy as installing https://github.com/karlseguin/pg.zig into zap and using that to build and run queries?
