### ISSUE TITLE
Zig 0.13 build error

### ISSUE THREAD

**Issue by Paul-0x5061756c** [zigzap/zap#109]
Following the Readme, you get the following error when trying to build.

`error: no field named 'path' in union 'Build.LazyPath'`

Build.zig
 ```
    const zap = b.dependency("zap", .{
        .target = target,
        .optimize = optimize,
        .openssl = false, // set to true to enable TLS support
    });

    exe.root_module.addImport("zap", zap.module("zap"));

    b.installArtifact(exe);
```

**Comment by stepasite** [comment]
I use master branch with zig 0.13.0 and my app runs OK. @Paul-0x5061756c

**Comment by crawftv** [comment]
> I use master branch with zig 0.13.0 and my app runs OK. @Paul-0x5061756c

@stepasite I'm struggling with this problem as well. If you don't mind me asking,
Did you use the setup instructions from the README.md in this repo? How did you install zig?
thanks,

**Comment by crawftv** [comment]
Looks like the lazy path should have been fixed with this PR. https://github.com/zigzap/zap/pull/105

**Comment by Fyphen1223** [comment]
The same problem here, how should I resolve it?

**Comment by Paul-0x5061756c** [comment]
If I'm not mistaken adding this line fixed it for me:

`exe.linkLibrary(zap.artifact("facil.io"));`

**Comment by Fyphen1223** [comment]
> If I'm not mistaken adding this line fixed it for me:
> 
> `exe.linkLibrary(zap.artifact("facil.io"));`

This didn't fix it for me.

**Comment by Paul-0x5061756c** [comment]
> > If I'm not mistaken adding this line fixed it for me:
> > `exe.linkLibrary(zap.artifact("facil.io"));`
> 
> This didn't fix it for me. Would you mind showing me build.zig.zon?

Yea I wouldn't mind, but I messed around with Zap and deleted the code after... sorry about that

**Comment by Fyphen1223** [comment]
> > > If I'm not mistaken adding this line fixed it for me:
> > > `exe.linkLibrary(zap.artifact("facil.io"));`
> > 
> > 
> > This didn't fix it for me. Would you mind showing me build.zig.zon?
> 
> Yea I wouldn't mind, but I messed around with Zap and deleted the code after... sorry about that

lol, please do not mind :)
I'm just a beginner of Zig so I might be making stupid mistakes...
