### ISSUE TITLE
How to serve an html template from a file? 

### ISSUE THREAD

**Issue by ally9335** [zigzap/zap#124]
There's no example in /examples but one for encoding it as Zig code.

**Comment by jeroenflvr** [comment]
For that purpose, and the ability to use data, I use the supported Mustache templating. Mustache has a 'fromFile()' method.

importing mustache 

```zig
const Mustache = @import("zap").Mustache;
```

and then just call fromFile()
```zig
var mustache = Mustache.fromFile("view/layout/base.html") catch return;
defer mustache.deinit();
```
