### ISSUE TITLE
TechBenchmark benchmark slow perfomance

### ISSUE THREAD

**Issue by dragosv** [zigzap/zap#129]
After fixing issue with external library and upgrading to 0.8 the benchmark finally works. However the achieved results are significantly slower than expected. Would appreciate help improving the performance.

https://www.techempower.com/benchmarks/#section=test&runid=235f2c13-5e49-44b8-9dc1-1d087d6353bc&hw=ph&test=db 

Code:
https://github.com/TechEmpower/FrameworkBenchmarks/tree/master/frameworks/Zig/zap

**Comment by dragosv** [comment]
Using multiple workers significantly increases performance

**Comment by i11010520** [comment]
How much performance will improve with that?

In the latest [TechEmpower](https://www.techempower.com/benchmarks/#section=data-r23&hw=ph&test=plaintext), zap still ranked low.
