### ISSUE TITLE
Windows Support | Build is failing for Windows Platform

### ISSUE THREAD

**Issue by Slendergo** [zigzap/zap#31]
When compiling on windows, there isn't the linux related code, macros and includes such as 

nanosleep
kill

<arpa/inet.h>
<sys/time.h>
<unistd.h>

etc

**Comment by renerocksai** [comment]
This is expected behavior, as zap is built upon facil.io.

My personal opinion: zap is meant for (serious) server business which rules out deploying on Windows hosts anyway. As I said, that's my personal opinion. 

If you want to play around with zap on Windows, please use WSL2.
