### ISSUE TITLE
zig compiler version

### ISSUE THREAD

**Issue by alexpyattaev** [zigzap/zap#38]
What is the zig version to run this project? 0.10.1 fails with silly errors, which one is needed is not listed anywhere...

**Comment by renerocksai** [comment]
As mentioned in [Getting Started](https://github.com/zigzap/zap#getting-started), it is the latest release: 0.11.0

**Comment by renerocksai** [comment]
Nevermind. Playing, even with compilers, is ultimately valuable. :smile:
