### ISSUE TITLE
Unable to build "run-hello" with current zig master (0.12.0-dev.934+a241cf90d)

### ISSUE THREAD

**Issue by dimsuz** [zigzap/zap#48]
Using zip version `0.12.0-dev.934+a241cf90d` (2023-10-16), I try to run sample, following the README:

```
$ git clone https://github.com/zigzap/zap.git
$ cd zap
$ zig build run-hello
```
and I get this error:

```
$ zig build run-hello 
.../zap/build.zig.zon:1:2: error: missing top-level 'paths' field
```

Never used zon, so perhaps I'm missing something (only learning zig).

**Comment by dimsuz** [comment]
Update: it works with `v0.11.0`, it seems that zap targets stable releases, in this case this issue is irrelevant, but still maybe something to take note of.

**Comment by renerocksai** [comment]
As explicitly stated in the README and indicated by the build badge, zap is intended for the latest zig release. Not a current dev version.
