### ISSUE TITLE
build.zig.zon requires path field

### ISSUE THREAD

**Issue by akhildevelops** [zigzap/zap#54]
In the latest version of ziglang, build.zig.zon requires path field to be decalred.

```zig
akhil@ad:~/practice/immich$ zig fetch --save https://github.com/zigzap/zap/tarball/master
/home/akhil/.cache/zig/tmp/fa6da82352a5a36d/build.zig.zon:1:2: error: missing top-level 'paths' field
.{
 ^
```

**Comment by renerocksai** [comment]
I thought the readme was quite clear that zap requires the latest stable zig release 0.11. Please, people, read the readme. It's called readme and not .gitignore 🙂 for a reason!

So this is not an issue, as the correct and sane versions are specified. If you use zig master, you operate outside of the specs and there will be problems, and more will come as zig master keeps progressing.

If you want to use the released version of zap, please use zig 0.11. Zap is not meant to be needed to be updated every two weeks, following zig master.

If you know that you only want zig master, hop on the discord and check out the discussions there. Contributors have their own forks of zap and facilio for zig 0.12, and are updating some PRs that I haven't had time to look at.

**Comment by akhildevelops** [comment]
Lol yaa I overlooked the required version (0.11.0). Was thinking to give PR to  master to be compatible with nightly zig. Anyways I made zap to work on nightly zig and I think I'll maintain my own fork until `zap` gets synced with zig's next release.

A small note, please put the line: `Make sure you have the latest zig release (0.11.0) installed. Fetch it from [here](https://ziglang.org/download).` anywhere in the top of readme so it would be easy to identify and first time users would be aware of incompatibility with nightly zig.

**Comment by renerocksai** [comment]
I totally agree! Let's make it less of a "haven't you read the fineprint?" situation 🙂.

There have been quite a few zig master forks popping up now... I hope I will have time to merge them into a branch over the holidays, when I also want to review and mildly refactor zap's API.

Especially since both the zig download page and projects like ziglings seem to nudge newcomers into going for zig master straight away.
