### ISSUE TITLE
Exposé API for fetching MIME type for given extension

### ISSUE THREAD

**Issue by hauleth** [zigzap/zap#65]
That would be really helpful for setting `content-type` header to proper values when you deal with something more than just JSON, HTML, and plain text.

**Comment by renerocksai** [comment]
Thank you for raising this. I am currently cleaning up the API and also noted that I only ever put 3 MIME types in the enum for SETTING it. (You can always set the header manually if you need other mime types though).

The function you are looking for is already present and called: `setContentTypeFromPath`. It sets the mime type header based on the path in the request and is used in the `hello2` example.

**Comment by hauleth** [comment]
@renerocksai yes, but it uses *request path*, and I am setting it to value that may differ from the request path extension. I want to be able to provide my own extension/filename. My current code for that is:

```zig
pub fn setContentTypeFromFilename(self: *const Self, filename: []const u8) !void {
    var ext = std.fs.path.extension(filename);

    if (ext.len > 1) {
        var e = ext[1..];
        var obj = zap.http_mimetype_find(@constCast(e.ptr), e.len);

        if (zap.fio2str(obj)) |mime_str| {
            try self.req.setHeader("content-type", mime_str);
        }
    }
}
```

**Comment by renerocksai** [comment]
So what you're saying is that you want this function to be merged into zap?

I can certainly do that.

**Comment by renerocksai** [comment]
I just put this into zap's Request struct and tested it via the hello example:

```zig
    /// Tries to determine the content type by filename extension, and sets it.
    /// If the extension cannot be determined, NoExtensionInFilename error is
    /// returned.
    pub fn setContentTypeFromFilename(self: *const Self, filename: []const u8) !void {
        const ext = std.fs.path.extension(filename);

        if (ext.len > 1) {
            var e = ext[1..];
            var obj = fio.http_mimetype_find(@constCast(e.ptr), e.len);

            if (util.fio2str(obj)) |mime_str| {
                try self.setHeader("content-type", mime_str);
            }
        } else {
            return error.NoExtensionInFilename;
        }
    }
```

I'll probably create a breaking (API cleanup) release very soon; your function will be in there :relaxed:
