### ISSUE TITLE
Represent request method as enum instead of string

### ISSUE THREAD

**Issue by hauleth** [zigzap/zap#67]
With enumerable it makes it *way* easier to setup routing or in general match against request method. There is even built in [`std.http.Method`](https://ziglang.org/documentation/0.11.0/std/#A;std:http.Method) enum that provides set of such methods available.

**Comment by egoholic** [comment]
I'm not sure if it makes sense because in a request a method is represented as a string and you need anyway to compare against string. For example, Golang's net/http package also defines methods as strings **https://pkg.go.dev/net/http#pkg-constants**
