### ISSUE TITLE
Failure to compile facil.io : unable to build C object: clang exited with code 1

### ISSUE THREAD

**Issue by SfundoMhlungu** [zigzap/zap#77]
Zig version:
  0.11.0

Machine: 
  Windows 11

Steps: 
      $ git clone https://github.com/zigzap/zap.git
      $ cd zap
      $ zig build run-hello

Truncated output:
    zig build-lib facil.io Debug native: error: the following command failed with 15 compilation errors:
C:\Users\mhlun\zig-x64-true-11\zig.exe build-lib -cflags -Wno-return-type-c-linkage -fno-sanitize=undefined -DFIO_HTTP_EXACT_LOGGING -- C:\Users\mhlun\fun\sys\zig\backend\zap\facil.io\lib\facil\fio.c C:\Users\mhlun\fun\sys\zig\backend\zap\facil.io\lib\facil\fio_zig.c C:\Users\mhlun\fun\sys\zig\backend\zap\facil.io\lib\facil\http\http.c C:\Users\mhlun\fun\sys\zig\backend\zap\facil.io\lib\facil\http\http1.c C:\Users\mhlun\fun\sys\zig\backend\zap\facil.io\lib\facil\http\websockets.c C:\Users\mhlun\fun\sys\zig\backend\zap\facil.io\lib\facil\http\http_internal.c C:\Users\mhlun\fun\sys\zig\backend\zap\facil.io\lib\facil\fiobj\fiobj_numbers.c C:\Users\mhlun\fun\sys\zig\backend\zap\facil.io\lib\facil\fiobj\fio_siphash.c C:\Users\mhlun\fun\sys\zig\backend\zap\facil.io\lib\facil\fiobj\fiobj_str.c C:\Users\mhlun\fun\sys\zig\backend\zap\facil.io\lib\facil\fiobj\fiobj_ary.c C:\Users\mhlun\fun\sys\zig\backend\zap\facil.io\lib\facil\fiobj\fiobj_data.c C:\Users\mhlun\fun\sys\zig\backend\zap\facil.io\lib\facil\fiobj\fiobj_hash.c C:\Users\mhlun\fun\sys\zig\backend\zap\facil.io\lib\facil\fiobj\fiobj_json.c C:\Users\mhlun\fun\sys\zig\backend\zap\facil.io\lib\facil\fiobj\fiobject.c C:\Users\mhlun\fun\sys\zig\backend\zap\facil.io\lib\facil\fiobj\fiobj_mustache.c C:\Users\mhlun\fun\sys\zig\backend\zap\facil.io\lib\facil\cli\fio_cli.c -lc --cache-dir C:\Users\mhlun\fun\sys\zig\backend\zap\zig-cache --global-cache-dir C:\Users\mhlun\AppData\Local\zig --name facil.io -static -I C:\Users\mhlun\fun\sys\zig\backend\zap\facil.io -I C:\Users\mhlun\fun\sys\zig\backend\zap\facil.io\lib\facil -I C:\Users\mhlun\fun\sys\zig\backend\zap\facil.io\lib\facil\fiobj -I C:\Users\mhlun\fun\sys\zig\backend\zap\facil.io\lib\facil\cli -I C:\Users\mhlun\fun\sys\zig\backend\zap\facil.io\lib\facil\http -I C:\Users\mhlun\fun\sys\zig\backend\zap\facil.io\lib\facil\http\parsers --listen=-
Build Summary: 0/4 steps succeeded; 1 failed (disable with --summary none)
run-hello transitive failure
└─ run hello transitive failure
   └─ zig build-exe hello Debug native transitive failure
      └─ zig build-lib facil.io Debug native 15 errors
C:\Users\mhlun\fun\sys\zig\backend\zap\facil.io\lib\facil\http\http1.c:1:1: error: unable to build C object: clang exited with code 1
C:\Users\mhlun\fun\sys\zig\backend\zap\facil.io\lib\facil\http\websockets.c:1:1: error: unable to build C object: clang exited with code 1
C:\Users\mhlun\fun\sys\zig\backend\zap\facil.io\lib\facil\fiobj\fiobj_hash.c:1:1: error: unable to build C object: clang exited with code 1
C:\Users\mhlun\fun\sys\zig\backend\zap\facil.io\lib\facil\fiobj\fiobj_mustache.c:1:1: error: unable to build C object: clang exited with code 1
C:\Users\mhlun\fun\sys\zig\backend\zap\facil.io\lib\facil\fiobj\fiobj_json.c:1:1: error: unable to build C object: clang exited with code 1
C:\Users\mhlun\fun\sys\zig\backend\zap\facil.io\lib\facil\fiobj\fiobj_ary.c:1:1: error: unable to build C object: clang exited with code 1
C:\Users\mhlun\fun\sys\zig\backend\zap\facil.io\lib\facil\http\http.c:1:1: error: unable to build C object: clang exited with code 1
C:\Users\mhlun\fun\sys\zig\backend\zap\facil.io\lib\facil\fio_zig.c:1:1: error: unable to build C object: clang exited with code 1
C:\Users\mhlun\fun\sys\zig\backend\zap\facil.io\lib\facil\fiobj\fiobject.c:1:1: error: unable to build C object: clang exited with code 1
C:\Users\mhlun\fun\sys\zig\backend\zap\facil.io\lib\facil\cli\fio_cli.c:1:1: error: unable to build C object: clang exited with code 1
C:\Users\mhlun\fun\sys\zig\backend\zap\facil.io\lib\facil\fiobj\fiobj_data.c:1:1: error: unable to build C object: clang exited with code 1
C:\Users\mhlun\fun\sys\zig\backend\zap\facil.io\lib\facil\fio.c:1:1: error: unable to build C object: clang exited with code 1
C:\Users\mhlun\fun\sys\zig\backend\zap\facil.io\lib\facil\fiobj\fiobj_str.c:1:1: error: unable to build C object: clang exited with code 1
C:\Users\mhlun\fun\sys\zig\backend\zap\facil.io\lib\facil\fiobj\fiobj_numbers.c:1:1: error: unable to build C object: clang exited with code 1
C:\Users\mhlun\fun\sys\zig\backend\zap\facil.io\lib\facil\http\http_internal.c:1:1: error: unable to build C object: clang exited with code 1

**I wish i could be more helpful but i genuinely don't know what's going on**

**Comment by renerocksai** [comment]
Please read the faq in the readme. Zap does not work on Windows. Use WSL2.

**Comment by SfundoMhlungu** [comment]
my bad my bad just seen the faq. i think its overshadowed by the text above. it works perfectly thanks.

**Comment by SfundoMhlungu** [comment]
> Please read the faq in the readme. Zap does not work on Windows. Use WSL2.

my bad my bad just seen the faq. i think its overshadowed by the text above. it works perfectly thanks.
